server {
    listen 80;
    server_name localhost;

    # 1. Sirve la página web de React
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # 2. Redirige a Ventas (Captura /api/v1/venta o /api/v1/ventas) 🚀
    location ~* ^/api/v1/venta {
        proxy_pass http://backend-venta-svc:8080; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # 3. Redirige a Despachos (Captura /api/v1/despacho o /api/v1/despachos) 📦
    location ~* ^/api/v1/despacho {
        proxy_pass http://backend-despacho-svc:8080; # <- Se queda en 8080 porque el Service recibe ahí
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
