apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: innovatech
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS innovatech_db;
    USE innovatech_db;

    -- 1. Creamos la tabla EXACTAMENTE como la espera tu clase Venta
    CREATE TABLE IF NOT EXISTS venta (
        id_venta BIGINT AUTO_INCREMENT PRIMARY KEY,
        direccion_compra VARCHAR(255) NOT NULL,
        valor_compra INT NOT NULL,
        fecha_compra DATE NOT NULL,
        despacho_generado BOOLEAN NOT NULL DEFAULT FALSE
    );

    -- 2. Insertamos usando los nombres de columna correctos
    INSERT INTO venta (direccion_compra, valor_compra, fecha_compra, despacho_generado) VALUES
    ('P Sherman Calle Wallabi 42 Syndey', 22990, '2024-02-02', false),
    ('Avenida siempre viva 69', 12590, '2024-03-05', false),
    ('Avenida Por atrás 1313', 13990, '2024-04-20', false),
    ('Calle presidente kirby 8528', 9990, '2024-04-15', false);