apiVersion: v1
kind: Secret
metadata:
  name: innovatech-db-secret
  namespace: innovatech
type: Opaque
stringData: # Usamos stringData para texto plano
  MYSQL_ROOT_PASSWORD: daskdfiusdhiweb
  MYSQL_USER: innovatech_app # MySQL usa MYSQL_USER, no APP_USER
  MYSQL_PASSWORD: daskdfiusdhiweb-innovatech
  MYSQL_DATABASE: innovatech_db